replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  APP_ENV: dev

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
